// UI
export const SOCKET_STATUS = 'SOCKET_STATUS';

export const BANNER_ADD = 'BANNER_ADD';
export const BANNER_REMOVE = 'BANNER_REMOVE';
export const BANNER_REMOVE_SOCKET = 'BANNER_REMOVE_SOCKET';

export const SEARCH_ITEMS = 'SEARCH_ITEMS';

export const SELF_LOGOUT_REQUEST = 'SELF_LOGOUT_REQUEST';
export const SELF_LOGOUT_SUCCESS = 'SELF_LOGOUT_SUCCESS';
export const SELF_LOGOUT_FAILURE = 'SELF_LOGOUT_FAILURE';


// ----
// DATA

// USER
export const SELF_FETCH_REQUEST = 'SELF_FETCH_REQUEST';
export const SELF_FETCH_REFETCH = 'SELF_FETCH_REFETCH';
export const SELF_FETCH_SUCCESS = 'SELF_FETCH_SUCCESS';
export const SELF_FETCH_FAILURE = 'SELF_FETCH_FAILURE';

// INSTANCES
export const INSTANCES_FETCH_REQUEST = 'INSTANCES_FETCH_REQUEST';
export const INSTANCES_FETCH_REFETCH = 'INSTANCES_FETCH_REFETCH';
export const INSTANCES_FETCH_SUCCESS = 'INSTANCES_FETCH_SUCCESS';
export const INSTANCES_FETCH_FAILURE = 'INSTANCES_FETCH_FAILURE';

export const INSTANCE_CREATE_REQUEST = 'INSTANCE_CREATE_REQUEST';
export const INSTANCE_CREATE_SUCCESS = 'INSTANCE_CREATE_SUCCESS';
export const INSTANCE_CREATE_FAILURE = 'INSTANCE_CREATE_FAILURE';

export const INSTANCE_UPDATE_REQUEST = 'INSTANCE_UPDATE_REQUEST';
export const INSTANCE_UPDATE_SUCCESS = 'INSTANCE_UPDATE_SUCCESS';
export const INSTANCE_UPDATE_FAILURE = 'INSTANCE_UPDATE_FAILURE';

export const INSTANCE_DELETE_REQUEST = 'INSTANCE_DELETE_REQUEST';
export const INSTANCE_DELETE_SUCCESS = 'INSTANCE_DELETE_SUCCESS';
export const INSTANCE_DELETE_FAILURE = 'INSTANCE_DELETE_FAILURE';

// ITEMS
export const ITEMS_FETCH_REQUEST = 'ITEMS_FETCH_REQUEST';
export const ITEMS_FETCH_REFETCH = 'ITEMS_FETCH_REFETCH';
export const ITEMS_FETCH_SUCCESS = 'ITEMS_FETCH_SUCCESS';
export const ITEMS_FETCH_FAILURE = 'ITEMS_FETCH_FAILURE';

export const ITEM_AUTOFILL_REQUEST = 'ITEM_AUTOFILL_REQUEST';
export const ITEM_AUTOFILL_SUCCESS = 'ITEM_AUTOFILL_SUCCESS';
export const ITEM_AUTOFILL_FAILURE = 'ITEM_AUTOFILL_FAILURE';

export const ITEM_CREATE_REQUEST = 'ITEM_CREATE_REQUEST';
export const ITEM_CREATE_SUCCESS = 'ITEM_CREATE_SUCCESS';
export const ITEM_CREATE_FAILURE = 'ITEM_CREATE_FAILURE';

export const ITEM_UPDATE_REQUEST = 'ITEM_UPDATE_REQUEST';
export const ITEM_UPDATE_SUCCESS = 'ITEM_UPDATE_SUCCESS';
export const ITEM_UPDATE_FAILURE = 'ITEM_UPDATE_FAILURE';

export const ITEM_DELETE_REQUEST = 'ITEM_DELETE_REQUEST';
export const ITEM_DELETE_SUCCESS = 'ITEM_DELETE_SUCCESS';
export const ITEM_DELETE_FAILURE = 'ITEM_DELETE_FAILURE';

// BUTTONS
export const BUTTONS_FETCH_REQUEST = 'BUTTONS_FETCH_REQUEST';
export const BUTTONS_FETCH_REFETCH = 'BUTTONS_FETCH_REFETCH';
export const BUTTONS_FETCH_SUCCESS = 'BUTTONS_FETCH_SUCCESS';
export const BUTTONS_FETCH_FAILURE = 'BUTTONS_FETCH_FAILURE';

export const BUTTON_CREATE_REQUEST = 'BUTTON_CREATE_REQUEST';
export const BUTTON_CREATE_SUCCESS = 'BUTTON_CREATE_SUCCESS';
export const BUTTON_CREATE_FAILURE = 'BUTTON_CREATE_FAILURE';

export const BUTTON_UPDATE_REQUEST = 'BUTTON_UPDATE_REQUEST';
export const BUTTON_UPDATE_SUCCESS = 'BUTTON_UPDATE_SUCCESS';
export const BUTTON_UPDATE_FAILURE = 'BUTTON_UPDATE_FAILURE';

export const BUTTON_DELETE_REQUEST = 'BUTTON_DELETE_REQUEST';
export const BUTTON_DELETE_SUCCESS = 'BUTTON_DELETE_SUCCESS';
export const BUTTON_DELETE_FAILURE = 'BUTTON_DELETE_FAILURE';


// ---
// RPC
export const RPC_SELF_FETCH = 'self_fetch';
export const RPC_SELF_UPDATE = 'self_update';

export const RPC_BUTTONS_FETCH = 'buttons_fetch';
export const RPC_BUTTON_CREATE = 'button_create';
export const RPC_BUTTON_UPDATE = 'button_update';
export const RPC_BUTTON_DELETE = 'button_delete';

export const RPC_INSTANCES_FETCH = 'instances_fetch';
export const RPC_INSTANCE_CREATE = 'instance_create';
export const RPC_INSTANCE_UPDATE = 'instance_update';
export const RPC_INSTANCE_DELETE = 'instance_delete';

export const RPC_ITEMS_FETCH = 'items_fetch';
export const RPC_ITEM_AUTOFILL = 'item_autofill';
export const RPC_ITEM_CREATE = 'item_create';
export const RPC_ITEM_UPDATE = 'item_update';
export const RPC_ITEM_DELETE = 'item_delete';


// -----------
// CHANGE FEED
export const FEED_BUTTONS_INSERT = 'feed_buttons_insert';
export const FEED_BUTTONS_UPDATE = 'feed_buttons_update';
export const FEED_BUTTONS_DELETE = 'feed_buttons_delete';

export const FEED_INSTANCES_INSERT = 'feed_instances_insert';
export const FEED_INSTANCES_UPDATE = 'feed_instances_update';
export const FEED_INSTANCES_DELETE = 'feed_instances_delete';

export const FEED_ITEMS_INSERT = 'feed_items_insert';
export const FEED_ITEMS_UPDATE = 'feed_items_update';
export const FEED_ITEMS_DELETE = 'feed_items_delete';
